import express from "express";
import { list, cancel, transfer, update, stats, checkIn, checkOut, markNoShow } from "../controllers/bookingMgmtController.js";
const router = express.Router();
router.get("/", list);
router.get("/stats", stats);
router.post("/:id/cancel", cancel);
router.post("/:id/transfer", transfer);
router.post("/:id/checkin", checkIn);
router.post("/:id/checkout", checkOut);
router.post("/:id/no-show", markNoShow);
router.patch("/:id", update);
export default router;