import express from "express";
import { listWallets, getHotelWallet, settle, summary, commissionReport, getGoodBizEligibility } from "../controllers/walletController.js";
const router = express.Router();
router.get("/", listWallets);
router.get("/summary", summary);
router.get("/commissions", commissionReport);
router.get("/eligibility/:hotelId", getGoodBizEligibility);
router.get("/hotel/:hotelId", getHotelWallet);
router.post("/settle", settle);
export default router;